const state = {
  stores: [],
  reviews: {},
  currentStore: null,
  status: {},
  aiProvider: 'auto',
};

// ── DOM helpers ──────────────────────────────────────────────────
const $ = (s, p) => (p || document).querySelector(s);
const $$ = (s, p) => [...(p || document).querySelectorAll(s)];
const esc = s => { const d = document.createElement('div'); d.textContent = s || ''; return d.innerHTML; };
const _shortName = name => { const i = name.indexOf(' - '); return i === -1 ? name : name.substring(i + 3); };

// ── Init ─────────────────────────────────────────────────────────
async function init() {
  try {
    state.status = await getStatus();
    renderHeader();
  } catch (e) { log(`Status load failed: ${e.message}`, 'error'); }
  try {
    state.stores = await getStores();
    renderStoreList();
  } catch (e) { log(`Stores load failed: ${e.message}`, 'error'); }

  $('#btn-refresh-all')?.addEventListener('click', async () => {
    log('Refreshing stores...', 'info');
    state.stores = await getStores();
    renderStoreList();
    if (state.currentStore) loadReviews(state.currentStore);
  });

  // Listen for provider radio changes
  document.querySelectorAll('input[name="aiProvider"]').forEach(r => {
    r.addEventListener('change', () => {
      state.aiProvider = r.value;
      renderModeToggle(state.status);
      log(`AI provider switched to ${r.value}`, 'info');
    });
  });
}

// ── Header ───────────────────────────────────────────────────────
function renderHeader() {
  const s = state.status;

  $('#status-badges').innerHTML = '';

  const btn = $('#btn-toggle-dryrun');
  const isDry = s.dryRun;
  btn.className = `text-xs px-3 py-1 rounded-full font-medium transition-colors border cursor-pointer ${
    isDry
      ? 'badge-dryrun'
      : 'badge-live'
  }`;
  btn.textContent = isDry ? '🔴 DRY RUN' : '🟢 LIVE';
  btn.classList.remove('hidden');
  btn.onclick = async () => {
    try {
      await setDryRun(!isDry);
      state.status = await getStatus();
      renderHeader();
      log(`Switched to ${state.status.dryRun ? 'DRY RUN' : 'LIVE'} mode`, 'info');
    } catch (e) {
      log(`Failed to toggle dry-run: ${e.message}`, 'error');
    }
  };

  renderModeToggle(s);
}

// ── Mode toggle ──────────────────────────────────────────────────
function renderModeToggle(s) {
  const mode = s.replyMode || 'llm';
  const providerLabels = { auto: 'Auto', ollama: 'Ollama', groq: 'Groq', gemini: 'Gemini' };
  const modeLabel = mode === 'llm' ? `LLM (${providerLabels[state.aiProvider] || 'Auto'})` : 'Templates';

  $('#mode-indicator').textContent = `Reply mode: ${modeLabel}`;

  const btns = $$('.mode-btn');
  btns.forEach(b => {
    const active = b.dataset.mode === mode;
    b.className = `mode-btn ${active ? 'active' : ''}`;
  });

  const detail = $('#mode-detail');
  if (detail) {
    if (mode === 'llm') {
      detail.innerHTML = `<strong class="text-royal-700">LLM mode</strong> — Replies are generated by the selected AI provider. Falls back to templates if the provider is unreachable.<br><span class="text-gray-400 mt-1 block leading-relaxed">Fallback chain: Ollama → Groq → Gemini → templates. GH secrets: <code class="bg-gray-200/60 px-1.5 py-0.5 rounded text-gray-500">GROQ_API_KEY</code>, <code class="bg-gray-200/60 px-1.5 py-0.5 rounded text-gray-500">GEMINI_API_KEY</code></span>`;
    } else {
      detail.innerHTML = `<strong class="text-gray-600">Template mode</strong> — Replies use pre-written templates from Google Sheets. Toggle to LLM for AI-generated replies.`;
    }
  }

  // Show/hide provider section
  const provSection = $('#ai-provider-section');
  if (provSection) {
    provSection.classList.toggle('hidden', mode !== 'llm');
  }

  // Sync radio state
  if (mode === 'llm') {
    const radio = document.querySelector(`input[name="aiProvider"][value="${state.aiProvider}"]`);
    if (radio) radio.checked = true;
  }

  btns.forEach(b => {
    b.onclick = async () => {
      try {
        await setReplyMode(b.dataset.mode);
        log(`Reply mode switched to ${b.dataset.mode}`, 'info');
        state.status = await getStatus();
        renderModeToggle(state.status);
      } catch (e) {
        log(`Failed to change mode: ${e.message}`, 'error');
      }
    };
  });
}

// ── Store list ───────────────────────────────────────────────────
function renderStoreList() {
  const totalPending = state.stores.reduce((sum, s) => {
    const c = parseInt(s.pending_count);
    return sum + (c > 0 ? c : 0);
  }, 0);
  const countEl = $('#total-pending-count');
  if (countEl) {
    countEl.textContent = `${totalPending} pending`;
    countEl.classList.remove('hidden');
  }

  const el = $('#store-list');
  el.innerHTML = state.stores.map(s => {
    const active = state.currentStore === s.short_name;
    const badge = s.pending_count === -1 ? '!' : s.pending_count;
    const badgeClass = s.pending_count === -1 ? 'store-badge error' : s.pending_count > 0 ? 'store-badge has-pending' : 'store-badge';
    return `
      <div class="store-item flex items-center gap-2 px-3 py-2 text-sm ${active ? 'active' : 'text-gray-600'}" data-store="${s.short_name}">
        <span class="${badgeClass}">${badge}</span>
        <span class="flex-1 truncate"><span class="font-medium">${esc(s.short_name)}</span><span class="text-gray-400 ml-1">${esc(_shortName(s.name))}</span></span>
      </div>
    `;
  }).join('');

  $$('.store-item').forEach(el => {
    el.addEventListener('click', () => {
      state.currentStore = el.dataset.store;
      renderStoreList();
      loadReviews(state.currentStore);
    });
  });
}

// ── Reviews ──────────────────────────────────────────────────────
async function loadReviews(storeShortName) {
  const el = $('#reviews-panel');
  el.innerHTML = '<div class="flex items-center justify-center h-full text-gray-400 text-sm"><div class="flex flex-col items-center gap-2"><svg class="animate-spin h-6 w-6 text-royal-400" viewBox="0 0 24 24" fill="none"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg><span>Loading reviews...</span></div></div>';
  try {
    const reviews = await getReviews(storeShortName, 20);
    state.reviews[storeShortName] = reviews;
    renderReviews(storeShortName);
  } catch (e) {
    el.innerHTML = `<div class="text-red-500 text-sm py-12 text-center">${esc(e.message)}</div>`;
    log(`Load failed: ${e.message}`, 'error');
  }
}

function renderReviews(storeShortName) {
  const el = $('#reviews-panel');
  const store = state.stores.find(s => s.short_name === storeShortName);
  const reviews = state.reviews[storeShortName] || [];
  const storeName = store ? store.name : storeShortName;

  if (reviews.length === 0) {
    el.innerHTML = `
      <div class="flex flex-col items-center justify-center h-full text-gray-400">
        <svg class="w-12 h-12 mb-4 text-gray-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <path d="M9 11l3 3L22 4"/>
          <path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/>
        </svg>
        <div class="text-sm font-medium text-gray-400">All caught up!</div>
        <div class="text-xs text-gray-400 mt-1">No pending reviews for <strong class="text-gray-500">${esc(storeName)}</strong>.</div>
        <button onclick="loadReviews('${storeShortName}')" class="mt-5 text-xs font-medium px-4 py-1.5 bg-royal-50 text-royal-700 border border-royal-200 rounded-lg hover:bg-royal-100 transition-colors">↻ Refresh</button>
      </div>
    `;
    return;
  }

  const repliedCount = reviews.filter(r => r.reviewReply).length;
  const pendingCount = reviews.length - repliedCount;
  el.innerHTML = `
    <div class="flex items-center justify-between mb-4">
      <div>
        <h3 class="text-sm font-bold text-gray-800">${esc(storeName)}</h3>
        <p class="text-xs text-gray-400 mt-0.5">${pendingCount} pending · ${reviews.length} total</p>
      </div>
      <div class="flex gap-2">
        <button onclick="loadReviews('${storeShortName}')" class="text-xs px-3 py-1.5 border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-500 transition-colors">↻ Refresh</button>
        <button onclick="generateAll('${storeShortName}')" class="text-xs px-3 py-1.5 bg-royal-600 text-white rounded-lg hover:bg-royal-700 transition-colors font-medium">Generate All</button>
      </div>
    </div>
    <div class="space-y-3" id="review-cards">
      ${reviews.map(r => renderReviewCard(r, storeShortName)).join('')}
    </div>
  `;
}

const STAR_MAP = { ONE: 1, TWO: 2, THREE: 3, FOUR: 4, FIVE: 5 };

function renderReviewCard(review, storeShortName) {
  const reviewer = review.reviewer?.displayName || 'Anonymous';
  const stars = STAR_MAP[review.starRating] || parseInt(review.starRating) || 0;
  const comment = review.comment || '(no text)';
  const starHtml = '⭐'.repeat(stars) + '☆'.repeat(5 - stars);
  const id = (review.name || review.reviewId || '').replace(/[^a-zA-Z0-9]/g, '_');
  const date = review.createTime ? new Date(review.createTime).toLocaleDateString() : '';
  const hasReply = !!review.reviewReply;
  const hasReplyBadge = hasReply ? '<span class="ml-2 inline-block text-xs font-medium text-green-600 bg-green-50 border border-green-200 rounded-full px-2 py-0.5">Replied</span>' : '';
  const cardOpacity = hasReply ? 'opacity-60' : '';

  return `
    <div class="review-card ${cardOpacity}" data-review-id="${id}">
      <div class="px-4 py-3 bg-gray-50/80 flex items-center justify-between">
        <div class="flex items-center gap-3">
          <div class="review-avatar">${reviewer.charAt(0).toUpperCase()}</div>
          <div>
            <span class="font-medium text-sm text-gray-800">${esc(reviewer)}</span>
            <span class="ml-2 text-sm">${starHtml}</span>
            ${date ? `<span class="ml-2 text-xs text-gray-400">${date}</span>` : ''}
            ${hasReplyBadge}
          </div>
        </div>
        <div class="flex gap-1.5">
          ${hasReply ? '' : `<button onclick="onGenerate(this)" data-store="${storeShortName}" class="text-xs px-3 py-1.5 bg-royal-600 text-white rounded-lg hover:bg-royal-700 transition-colors font-medium">Generate Reply</button>`}
        </div>
      </div>
      <div class="px-4 py-3 text-sm text-gray-600 bg-white leading-relaxed">${esc(comment)}</div>
      <div class="reply-area px-4 pb-3 bg-white hidden"></div>
    </div>
  `;
}

async function onGenerate(btn) {
  btn.disabled = true;
  btn.innerHTML = '<span class="inline-block animate-pulse">Generating...</span>';
  const card = btn.closest('[data-review-id]');
  const storeShortName = btn.dataset.store;
  const review = findReview(storeShortName, card.dataset.reviewId);
  if (!review) { log('Review not found', 'error'); btn.disabled = false; btn.textContent = 'Generate Reply'; return; }

  const providerLabel = state.aiProvider === 'auto' ? 'Auto' : state.aiProvider;
  log(`Generating reply for ${review.reviewer?.displayName || 'Anonymous'} via ${providerLabel}...`, 'info');

  try {
    const result = await generateReply(storeShortName, review, state.aiProvider);
    const area = card.querySelector('.reply-area');
    area.innerHTML = `
      <div class="mt-2 border border-royal-200 bg-royal-50/50 rounded-lg p-4">
        <div class="text-xs text-royal-700 font-semibold mb-2">✏️ Generated Reply — edit before posting</div>
        <textarea class="reply-text w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm bg-white focus:border-royal-400 focus:ring-2 focus:ring-royal-100 outline-none resize-none transition-shadow" rows="8">${esc(result.reply)}</textarea>
        <div class="flex gap-2 mt-3">
          <button onclick="onPost(this)" data-store="${storeShortName}" class="text-xs px-4 py-1.5 bg-royal-600 text-white rounded-lg hover:bg-royal-700 transition-colors font-medium">Post to Google</button>
          <button onclick="onGenerate(this)" data-store="${storeShortName}" class="text-xs px-4 py-1.5 border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-500 transition-colors">↻ Regenerate</button>
        </div>
      </div>
    `;
    area.classList.remove('hidden');
    log(`Reply generated for ${review.reviewer?.displayName || 'Anonymous'}`, 'info');
  } catch (e) { log(`Generate failed: ${e.message}`, 'error'); }
  btn.disabled = false;
  btn.textContent = 'Generate Reply';
}

async function onPost(btn) {
  btn.disabled = true;
  btn.innerHTML = '<span class="inline-block animate-pulse">Posting...</span>';
  const card = btn.closest('[data-review-id]');
  const storeShortName = btn.dataset.store;
  const review = findReview(storeShortName, card.dataset.reviewId);
  const replyText = card.querySelector('.reply-text')?.value;
  if (!review || !replyText) return;

  try {
    const result = await postReply(storeShortName, review, replyText);
    const label = result.dryRun ? '⚪ DRY RUN' : '✅ Posted';
    log(`${label} — ${review.reviewer?.displayName || 'Anonymous'}`, result.dryRun ? 'warn' : 'success');
    card.style.opacity = '0.4';
    card.querySelector('.reply-area').innerHTML = `
      <div class="mt-2 bg-royal-50 border border-royal-200 rounded-lg px-4 py-3">
        <div class="text-xs ${result.dryRun ? 'text-gold-500' : 'text-royal-700'} font-semibold flex items-center gap-1.5">
          <span>${result.dryRun ? '⚪' : '✅'}</span>
          ${result.dryRun ? 'DRY RUN — not posted' : 'Posted to Google'}
        </div>
      </div>
    `;
  } catch (e) { log(`Post failed: ${e.message}`, 'error'); }
}

function findReview(storeShortName, reviewId) {
  return (state.reviews[storeShortName] || []).find(r => {
    const id = (r.name || r.reviewId || '').replace(/[^a-zA-Z0-9]/g, '_');
    return id === reviewId;
  });
}

async function generateAll(storeShortName) {
  const cards = $$('#review-cards [onclick*="onGenerate"]');
  log(`Generating ${cards.length} replies...`, 'info');
  for (const btn of cards) {
    if (btn.disabled) continue;
    btn.click();
    await new Promise(r => setTimeout(r, 800));
  }
}

// ── Activity log ────────────────────────────────────────────────
function log(message, type = 'info') {
  const el = $('#activity-log');
  const time = new Date().toLocaleTimeString();
  const colors = { info: 'text-blue-600', success: 'text-green-600', error: 'text-red-600', warn: 'text-yellow-600' };
  const icons = { info: '→', success: '✅', error: '❌', warn: '⚪' };
  el.insertAdjacentHTML('afterbegin',
    `<div class="activity-entry ${colors[type] || 'text-gray-500'}">
      <span class="activity-icon">${icons[type] || '·'}</span>
      <span class="activity-msg">${esc(message)}</span>
      <span class="activity-time">${time}</span>
    </div>`
  );
}

// ── Bootstrap ───────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', init);
