#!/usr/bin/env python3
"""
Campaign Engine
Unified pipeline for all campaign types:
  offer | festival | greeting | update | announcement | testimonial

Pipeline per campaign:
  1. Validate (approval_status, is_expired, date range)
  2. Resolve store targeting (target_all_stores / target_store_n*)
  3. Check media (has_media + Drive image match)
  4. Generate image via Pillow if has_media=No and no Drive image
  5. Publish to social (Facebook, Instagram, Google) if social_enabled
  6. Mark expired campaigns after end_date
  7. Route to website build if post_website=Yes (or default)

Add a new campaign type by registering it in CAMPAIGN_TYPES below.
"""

import os
import shutil
from datetime import datetime
from zoneinfo import ZoneInfo

from content_engine import ContentEngine

# ── Supported campaign types ──────────────────────────────────────────────────
# Each type maps to its asset folder under assets/<type>/
# Add new types here — no other code changes needed.
CAMPAIGN_TYPES = [
    "offer",
    "festival",
    "greeting",
    "update",
    "announcement",
    "testimonial",
]

IST = ZoneInfo("Asia/Kolkata")

# Asset folder layout per campaign type
FOLDER_DOWNLOADED  = "01_downloaded"
FOLDER_PROCESSING  = "02_processing"
FOLDER_PUBLISHED   = "03_published"
FOLDER_ARCHIVED    = "04_archived"
FOLDER_FACEBOOK    = "facebook"
FOLDER_INSTAGRAM   = "instagram"

ASSETS_ROOT = "campaigns"

# ── Social publishing rules per campaign type ─────────────────────────────────
# Defines which platforms a type publishes to BY DEFAULT.
# The sheet fields (post_facebook, post_instagram, post_google) always override.
# offer → all platforms (fb + insta + google)
# others → fb + insta only by default; google only if post_google=Yes in sheet
SOCIAL_DEFAULTS = {
    "offer":        {"facebook": True,  "instagram": True,  "google": True},
    "festival":     {"facebook": True,  "instagram": True,  "google": False},
    "greeting":     {"facebook": True,  "instagram": True,  "google": False},
    "update":       {"facebook": True,  "instagram": True,  "google": True},
    "announcement": {"facebook": True,  "instagram": True,  "google": True},
    "testimonial":  {"facebook": True,  "instagram": False, "google": False},
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _asset_dir(campaign_type: str, subfolder: str) -> str:
    path = os.path.join(ASSETS_ROOT, campaign_type, subfolder)
    os.makedirs(path, exist_ok=True)
    return path


def _log(msg: str):
    print(datetime.now(IST).strftime("%H:%M:%S"), msg)


# ── Folder setup ──────────────────────────────────────────────────────────────

def setup_campaign_folders() -> None:
    """
    Ensure the full folder structure exists for every campaign type:

      assets/<type>/01_downloaded/
      assets/<type>/02_processing/
      assets/<type>/03_published/
      assets/<type>/04_archived/
      assets/<type>/facebook/
      assets/<type>/instagram/

    Safe to call on every run — os.makedirs with exist_ok=True is a no-op
    when folders already exist.
    """
    subfolders = [
        FOLDER_DOWNLOADED,
        FOLDER_PROCESSING,
        FOLDER_PUBLISHED,
        FOLDER_ARCHIVED,
        FOLDER_FACEBOOK,
        FOLDER_INSTAGRAM,
    ]
    for campaign_type in CAMPAIGN_TYPES:
        for sub in subfolders:
            path = os.path.join(ASSETS_ROOT, campaign_type, sub)
            os.makedirs(path, exist_ok=True)
    _log("📁 Campaign folders ready")


# ── Image resolution ──────────────────────────────────────────────────────────

def resolve_image(campaign: dict, campaign_type: str, drive_service=None, campaign_type_override: str = None) -> dict:
    """
    Determine image availability for a campaign.

    Returns updated campaign dict with keys:
      _image_path      – absolute path to published image (or "")
      _image_resolved  – True if image is ready
      _image_generated – True if image was generated by Pillow this run
    """
    engine = ContentEngine()
    asset_name = engine.get_field(campaign, "media_asset_name")
    has_media   = engine.has_media(campaign)
    published_dir = _asset_dir(campaign_type, FOLDER_PUBLISHED)
    
    # Use the provided campaign_type or fall back to the campaign's content_type
    search_campaign_type = campaign_type_override or campaign_type
    
    result = dict(campaign)
    result["_image_path"]      = ""
    result["_image_resolved"]  = False
    result["_image_generated"] = False

    if not asset_name:
        return result

    # Check if image already exists in 03_published
    for ext in [".jpg", ".jpeg", ".png", ".webp"]:
        candidate = os.path.join(published_dir, asset_name + ext)
        if os.path.exists(candidate):
            result["_image_path"]     = candidate
            result["_image_resolved"] = True
            return result

    # If not found locally, check Google Drive (only if has_media and drive_service available)
    if has_media and drive_service:
        from drive_offers import scan_staff_uploads
        
        # Search in the correct campaign type folder
        files = scan_staff_uploads(search_campaign_type)
        _log(f"🔍 Searching Google Drive for {asset_name} in {search_campaign_type} folder...")
        _log(f"   Found {len(files)} files in Drive")
        
        for file_info in files:
            base_name = os.path.splitext(file_info["name"])[0]
            _log(f"   Checking: {file_info['name']} (base: {base_name})")
            if base_name.lower() == asset_name.lower():
                # Found matching file in Drive
                _log(f"✅ Found matching file in Drive: {file_info['name']} (ID: {file_info['id']})")
                result["_image_resolved"] = True
                result["_drive_file_id"] = file_info["id"]
                
                # Download the file to local published folder
                downloaded_path = _download_from_drive(asset_name, search_campaign_type, drive_service)
                if downloaded_path:
                    result["_image_path"] = downloaded_path
                    _log(f"✅ Downloaded image to: {downloaded_path}")
                break
        else:
            _log(f"❌ No matching file found in Drive for {asset_name}")
    elif has_media:
        _log(f"⏭️  Skipping Drive search (no drive service available)")
    else:
        # has_media=No → generate with Pillow
        generated = _generate_image(result, campaign_type)
        if generated:
            result["_image_path"]      = generated
            result["_image_resolved"]  = True
            result["_image_generated"] = True

    return result


def _download_from_drive(asset_name: str, campaign_type: str, drive_service) -> str:
    """
    Search Google Drive staff uploads folder for the asset and download it.
    Returns local path on success, empty string on failure.
    """
    try:
        uploads_folder = f"campaigns/{campaign_type}/01_staff_uploads"
        # Search for file by name prefix (without extension)
        query = f"name contains '{asset_name}' and trashed = false"
        results = drive_service.files().list(
            q=query, fields="files(id, name)", pageSize=10
        ).execute()
        files = results.get("files", [])

        for f in files:
            fname = f["name"]
            base  = os.path.splitext(fname)[0]
            if base.lower() == asset_name.lower():
                dest_dir = _asset_dir(campaign_type, FOLDER_DOWNLOADED)
                dest     = os.path.join(dest_dir, fname)
                _download_drive_file(drive_service, f["id"], dest)
                # Move to published
                published = _asset_dir(campaign_type, FOLDER_PUBLISHED)
                final     = os.path.join(published, fname)
                shutil.move(dest, final)
                _log(f"✅ Downloaded from Drive: {fname}")
                return final
    except Exception as e:
        _log(f"⚠️  Drive download failed for {asset_name}: {e}")
    return ""


def _download_drive_file(drive_service, file_id: str, dest_path: str):
    import requests as req
    url     = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
    headers = {"Authorization": f"Bearer {drive_service._http.credentials.token}"}
    r       = req.get(url, headers=headers)
    with open(dest_path, "wb") as f:
        f.write(r.content)


def _generate_image(campaign: dict, campaign_type: str) -> str:
    """
    Generate a branded image using Pillow when has_media=No.
    Saves to assets/<type>/03_published/<asset_name>.jpg
    Returns path on success, empty string on failure.
    """
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        _log("⚠️  Pillow not installed — cannot generate image")
        return ""

    engine     = ContentEngine()
    asset_name = engine.get_field(campaign, "media_asset_name")
    title      = engine.get_field(campaign, "content_title") or campaign_type.title()
    body       = engine.get_field(campaign, "content_body") or ""
    start_date = engine.get_field(campaign, "start_date") or ""
    end_date   = engine.get_field(campaign, "end_date") or ""

    # Brand colours per type
    BG_COLOURS = {
        "offer":        "#632b6f",
        "festival":     "#b5451b",
        "greeting":     "#1b6b45",
        "update":       "#1b3d6b",
        "announcement": "#4a4a4a",
        "testimonial":  "#2b4b6f",
    }
    bg_colour = BG_COLOURS.get(campaign_type, "#632b6f")

    def _make(w: int, h: int, path: str):
        img  = Image.new("RGB", (w, h), bg_colour)
        draw = ImageDraw.Draw(img)

        # Fonts — try system fonts, fall back to default
        def _font(size):
            for name in [
                "/System/Library/Fonts/Arial.ttf",
                "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
                "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
            ]:
                try:
                    return ImageFont.truetype(name, size)
                except Exception:
                    pass
            return ImageFont.load_default()

        font_type  = _font(int(h * 0.04))
        font_title = _font(int(h * 0.07))
        font_body  = _font(int(h * 0.04))
        font_date  = _font(int(h * 0.03))

        # Type badge
        draw.text((40, 30), campaign_type.upper(), fill="#ffffff80", font=font_type)

        # Title (word-wrap)
        words, line, lines = title.split(), "", []
        for word in words:
            test = f"{line} {word}".strip()
            bbox = draw.textbbox((0, 0), test, font=font_title)
            if bbox[2] - bbox[0] > w - 80:
                lines.append(line)
                line = word
            else:
                line = test
        if line:
            lines.append(line)

        y = int(h * 0.25)
        for ln in lines[:3]:
            draw.text((40, y), ln, fill="white", font=font_title)
            y += int(h * 0.09)

        # Body (max 3 lines)
        if body:
            y += 20
            bwords, bline, blines = body.split(), "", []
            for word in bwords:
                test = f"{bline} {word}".strip()
                bbox = draw.textbbox((0, 0), test, font=font_body)
                if bbox[2] - bbox[0] > w - 80:
                    blines.append(bline)
                    bline = word
                else:
                    bline = test
            if bline:
                blines.append(bline)
            for ln in blines[:3]:
                draw.text((40, y), ln, fill="#f0f0f0", font=font_body)
                y += int(h * 0.055)

        # Date range
        if start_date or end_date:
            date_text = f"Valid: {start_date} – {end_date}" if end_date else f"From: {start_date}"
            draw.text((40, h - 80), date_text, fill="#ffd700", font=font_date)

        # Brand footer
        draw.text((40, h - 40), "NATURALS SALON & SPA", fill="#ffffff80", font=font_date)

        img.save(path, quality=92)

    published_dir = _asset_dir(campaign_type, FOLDER_PUBLISHED)
    fb_dir        = _asset_dir(campaign_type, FOLDER_FACEBOOK)
    ig_dir        = _asset_dir(campaign_type, FOLDER_INSTAGRAM)

    website_path   = os.path.join(published_dir, f"{asset_name}.jpg")
    facebook_path  = os.path.join(fb_dir,        f"{asset_name}_facebook.jpg")
    instagram_path = os.path.join(ig_dir,        f"{asset_name}_instagram.jpg")

    try:
        _make(1200, 1200, website_path)
        _make(1200, 630,  facebook_path)
        _make(1080, 1920, instagram_path)
        _log(f"🖼️  Generated image: {asset_name} ({campaign_type})")
        return website_path
    except Exception as e:
        _log(f"⚠️  Image generation failed for {asset_name}: {e}")
        return ""


# ── Social publishing ─────────────────────────────────────────────────────────

def _should_publish_platform(campaign: dict, campaign_type: str,
                              platform: str, engine: ContentEngine) -> bool:
    """
    Decide whether to publish to a platform for this campaign.

    Priority order:
      1. Sheet field (post_facebook / post_instagram / post_google) — explicit Yes/No
      2. SOCIAL_DEFAULTS per campaign type
      3. Fall back to social_enabled flag
    """
    sheet_field = f"post_{platform}"
    sheet_value = engine.get_field(campaign, sheet_field, "")

    if sheet_value:                          # explicit override in sheet
        return engine._is_yes(sheet_value)

    # Use type default
    defaults = SOCIAL_DEFAULTS.get(campaign_type, {})
    if platform in defaults:
        return defaults[platform]

    # Last resort: general social_enabled
    return engine.is_social_enabled(campaign)


def publish_to_social(campaign: dict, campaign_type: str, active_stores: list,
                      publisher=None) -> dict:
    """
    Publish campaign to the correct platforms for each targeted store.

    Platform rules (sheet fields always override):
      offer        → Facebook + Instagram + Google
      festival     → Facebook + Instagram
      greeting     → Facebook + Instagram
      update       → Facebook + Instagram + Google
      announcement → Facebook + Instagram + Google
      testimonial  → Facebook only

    Returns dict of results keyed by store_id.
    """
    engine = ContentEngine()

    if not engine.is_social_enabled(campaign):
        return {}

    if publisher is None:
        try:
            from social_publisher import SocialPublisher
            publisher = SocialPublisher()
        except ImportError:
            _log("⚠️  SocialPublisher not available")
            return {}

    asset_name = engine.get_field(campaign, "media_asset_name")
    fb_dir     = _asset_dir(campaign_type, FOLDER_FACEBOOK)
    ig_dir     = _asset_dir(campaign_type, FOLDER_INSTAGRAM)
    fb_image   = os.path.join(fb_dir, f"{asset_name}_facebook.jpg") if asset_name else None
    ig_image   = os.path.join(ig_dir, f"{asset_name}_instagram.jpg") if asset_name else None

    do_fb     = _should_publish_platform(campaign, campaign_type, "facebook",  engine)
    do_ig     = _should_publish_platform(campaign, campaign_type, "instagram", engine)
    do_google = _should_publish_platform(campaign, campaign_type, "google",    engine)

    results = {}
    for store in active_stores:
        store_id = engine.get_field(store, "Store_ID")

        if not engine.targets_store(campaign, store_id):
            continue

        store_name   = engine.get_field(store, "store_display_name")
        store_results = {"facebook": False, "instagram": False, "google": False}

        if do_fb:
            try:
                store_results["facebook"] = publisher.publish_to_facebook(
                    campaign, store_name,
                    engine.get_field(store, "facebook_page_id"),
                    fb_image if fb_image and os.path.exists(fb_image) else None
                )
            except Exception as e:
                _log(f"⚠️  Facebook publish error ({store_id}): {e}")

        if do_ig:
            try:
                store_results["instagram"] = publisher.publish_to_instagram(
                    campaign, store_name,
                    engine.get_field(store, "instagram_business_account_id"),
                    ig_image if ig_image and os.path.exists(ig_image) else None
                )
            except Exception as e:
                _log(f"⚠️  Instagram publish error ({store_id}): {e}")

        if do_google:
            try:
                google_fn = getattr(publisher, "publish_to_google", None)
                if google_fn:
                    store_results["google"] = google_fn(
                        campaign, store_name,
                        engine.get_field(store, "google_location_id"),
                    )
                else:
                    _log(f"⚠️  Google publish not implemented in SocialPublisher")
            except Exception as e:
                _log(f"⚠️  Google publish error ({store_id}): {e}")

        results[store_id] = store_results
        _log(f"📣 [{campaign_type}] → {store_id} fb={store_results['facebook']} "
             f"ig={store_results['instagram']} g={store_results['google']}")

    return results


# ── Expiry ────────────────────────────────────────────────────────────────────

def mark_expired_campaigns(campaigns: list, now_ist: datetime = None) -> list:
    """
    Move images of expired campaigns to 04_archived.
    Returns list of campaign dicts with is_expired set to 'Yes' for expired ones.
    """
    if now_ist is None:
        now_ist = datetime.now(IST)

    engine  = ContentEngine()
    updated = []

    for c in campaigns:
        c2 = dict(c)
        if not engine.is_expired(c) and not engine.is_valid_date_range(c):
            # Past end_date — archive image
            campaign_type = engine.get_content_type(c)
            asset_name    = engine.get_field(c, "media_asset_name")
            if asset_name and campaign_type in CAMPAIGN_TYPES:
                published_dir = _asset_dir(campaign_type, FOLDER_PUBLISHED)
                archive_dir   = _asset_dir(campaign_type, FOLDER_ARCHIVED)
                for ext in [".jpg", ".jpeg", ".png", ".webp"]:
                    src = os.path.join(published_dir, asset_name + ext)
                    if os.path.exists(src):
                        dst = os.path.join(archive_dir, asset_name + ext)
                        shutil.move(src, dst)
                        _log(f"📦 Archived expired campaign image: {asset_name}{ext}")
            c2["is_expired"] = "Yes"
        updated.append(c2)

    return updated


# ── Main pipeline ─────────────────────────────────────────────────────────────

def process_campaigns(campaigns: list, active_stores: list,
                      drive_service=None, publisher=None,
                      enable_social: bool = False) -> dict:
    """
    Full campaign pipeline for all campaign types.

    Args:
        campaigns:      Raw list of campaign dicts from Google Sheets / YAML
        active_stores:  List of active store dicts
        drive_service:  Google Drive service (optional)
        publisher:      SocialPublisher instance (optional)
        enable_social:  Whether to actually post to social media

    Pipeline steps:
      0. setup_campaign_folders  — create assets/<type>/0x_* dirs
      1. mark_expired_campaigns  — archive images, set is_expired=Yes
      2. Validate                — approval_status, is_expired, date range
      3. resolve_image           — Drive check → Pillow generation
      4. publish_to_social       — type-aware platform routing
      5. Bucket by type
      6. Website routing

    Returns:
        {
          "by_type": {
              "offer":        [enriched campaign dicts],
              "festival":     [...],
              ...
          },
          "for_website": [campaigns with post_website=Yes (or default)],
          "expired":     [campaigns marked expired this run],
        }
    """
    engine   = ContentEngine()
    now_ist  = datetime.now(IST)

    # Step 0: Ensure all campaign asset folders exist
    setup_campaign_folders()

    # Step 1: Mark expired campaigns (archive images, set is_expired=Yes)
    campaigns = mark_expired_campaigns(campaigns, now_ist)

    by_type    = {t: [] for t in CAMPAIGN_TYPES}
    for_website = []
    expired     = []

    for campaign in campaigns:
        content_type = engine.get_content_type(campaign)

        # Skip unknown types (still extendable — just add to CAMPAIGN_TYPES)
        if content_type not in CAMPAIGN_TYPES:
            _log(f"⚠️  Unknown campaign type '{content_type}' — skipping")
            continue

        # Step 2: Validate
        if not engine.is_approved(campaign):
            continue
        if engine.is_expired(campaign):
            expired.append(campaign)
            continue
        if not engine.is_valid_date_range(campaign):
            expired.append(campaign)
            continue

        # Step 3: Resolve image (Drive check → Pillow generation)
        campaign = resolve_image(campaign, content_type, drive_service, content_type)

        # Step 4: Social publishing
        if enable_social and engine.is_social_enabled(campaign):
            publish_to_social(campaign, content_type, active_stores, publisher)

        # Step 4.5: Mark Drive file as processed (if found and campaign processed successfully)
        if campaign.get("_drive_file_id") and campaign.get("_image_resolved"):
            try:
                from drive_offers import mark_drive_file_processed
                asset_name = engine.get_field(campaign, "media_asset_name")
                drive_file_id = campaign["_drive_file_id"]
                filename = f"{asset_name}.jpg"  # Assume .jpg extension
                
                if mark_drive_file_processed(drive_file_id, filename):
                    _log(f"✅ Marked Drive file as processed: {filename}")
                else:
                    _log(f"⚠️  Failed to mark Drive file as processed: {filename}")
            except Exception as e:
                _log(f"⚠️  Error marking Drive file as processed: {e}")

        # Step 5: Bucket by type
        by_type[content_type].append(campaign)

        # Step 6: Website routing
        if engine.should_show_on_website(campaign):
            for_website.append(campaign)

    # Log summary
    for t, items in by_type.items():
        if items:
            _log(f"✅ [{t}] {len(items)} active campaign(s)")

    return {
        "by_type":     by_type,
        "for_website": for_website,
        "expired":     expired,
    }


def get_campaigns_for_store(campaigns: list, store_id: str,
                             content_type: str = None) -> list:
    """
    Filter campaigns for a specific store, optionally by content_type.
    Campaigns must already be validated (pass through process_campaigns first).
    """
    engine = ContentEngine()
    result = []
    for c in campaigns:
        if content_type and engine.get_content_type(c) != content_type:
            continue
        if engine.targets_store(c, store_id):
            result.append(c)
    return result
